travis:
  secure:
    BINSTAR_TOKEN: XEZxv2X9RbE/jNAEdkwasHRkxyhj9yIeL2uyzsDH/C8Q1+zVC4bK2v7edDVTJXwihWSx3uKq65qUxTYI3tdzaMhiTOALIhTkUky6nSSTqPMn7qFgsuCnTCnuHSOwfsaY3iAJ9BjCkuuMJhyWQjrcR42XJTo5P5awuo3GlwbbfgtoAeORJZxYgFHN9dC2euLbINwvF2u7Ip+tAtjtyeU2x/CY0MLHxPuc1x+a5s566y5FU6n3AEnoFTKU13DeFrAsQr/EUoNNutkCjR8kbD1QZeiyPeR56QaxO0UBigCpO3ImBtMLt2Twj1PvenR57ZjvhMJ14OwLixtfWH745T9mh/cwYO5/karrU40YCgNHubyCMD5nIuwGbetPolK2rXPFcwLKf0bqZUY5Tu+94CVbxL0bs4D7FH18h2MRUp8yVXWLWiy7ROj5vXxFF1FmZGJoqCjWs9jY6QBLkv9kNYLMyjpldCRSOFzSH8GCRZc8E50xsDqNtZx1dqhq0T50sHku/6JGmuoKfJpjQjdQNXYppIaJxya/5Zjd5Wf9yXUvDxRiMIWk5V7yrTj1VCXBzl4hpetAXAw+5OsyvnnqXLjbIcq+eJv0DcYNWzACBn60XrE3+Cq0DDhO/ORSiHgRgo5bN7pKtbQWyxewQXUA6N83jImc2ww7vrHVrpJjhPT4MTw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
