travis:
  secure:
    BINSTAR_TOKEN: Uqa+0//j2H2zGdbXxVK/ir+e9/aUJdXcMeuGKYWUxP5pagP7wFnazRm2zCeV8AQ/8PuVvrOvHRtYEM5aJeu2K4su2q9Thp3g7R2SCAwMs8qlOTgkbz6HgAIZQoWlfGi9uBNMd55WquRLn/olOuC1JWkVUTg1NVL5+tEAyGkHFJCBFLJUgTiQbQmpdMRO+KgduURN/6z2Y/ZQN0do8Iu4l1ii4VpAMNq6g0hNY5bqnPKBQZ2cidxWuK468ikhmCFXcDmEipE3e+uIrU3OYkuKGLxGMIanBZ/Qz3gHuZMLhMQkDTC/JkC8ZhEj2U9belw34nzY7euizD93Dk9G/fCEmCRzOM4+2KX6UyLqxoBU5UyVKzbz+axC1bt+RgxY61zFA4dmJQmuJa1di9A5LbkX/5VZQqD/nzIGB0mqGzeq25m5NrL9ACO5dqgRkUWu7XKE1wUVu1GZYrRAnYuxe9kpLg/tX/t0nyF8J2vgYCk72eBMJukzva4L/mEVLz0WnArDh81fxgfbP88NATUJmj7PsTGEC+t8kPIC8PJ5LAqgCpOgV1RcPhAuwFLDdHYEG4YhNWvnnsPk1J2GAKC1cNduMsxYAa7qDpJl87FYg08VEFuED6AIt6fqVdlQLU/dDMIlBS+IP4D/AN2xPoO9Tlbh2KoNs6H5IFxFX+9XhhUP1Yc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
